@startuml
package Direct3D12
{
    class IDXGIFactory
    class IDXGIAdapter
    class ID3D12Device

    IDXGIAdapter --* IDXGIFactory
    ID3D12Device --* IDXGIAdapter
    IID3D12CommandQueue --* ID3D12Device
    IDXGISwapChain --* IDXGIFactory
    ID3D12CommandAllocator --* ID3D12Device
}

package Vulkan
{
    class VkInstance
    class VkPhysicalDevice
    class VkDevice
    class VkQueue

    VkPhysicalDevice --* VkInstance
    VkDevice --* VkPhysicalDevice
    VkQueue --* VkDevice
    VkCommandPool --* VkDevice
    VkCommandBuffer --* VkDevice
    VkFence --* VkDevice
    VkSemaphore --* VkDevice
    VkSurfaceKHR --* VkInstance
    VkSwapChainKHR --* VkDevice
}
@enduml