@startuml Loops

start
:Initialize;
repeat
    :Process Player Input;
    :Perform Game Logic\n(AI, Physics, World Simulation, etc.);
    :Render Scene, Play SFX, etc.;
repeat while (shutdown?) is (no)
->yes;
:Shutdown;
end

@enduml