#!/usr/bin/env python3
"""Generate lightweight image variants and an image manifest.

The script intentionally has one dependency: Pillow. It writes WebP variants for
large local images when the result is smaller than the source, then records image
dimensions and byte sizes in _data/image_manifest.yml.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parents[1]
IMAGE_ROOT = ROOT / "assets" / "images"
MANIFEST = ROOT / "_data" / "image_manifest.yml"
SOURCE_SUFFIXES = {".gif", ".jpg", ".jpeg", ".png"}


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def image_info(path: Path) -> dict[str, object] | None:
    try:
        with Image.open(path) as image:
            return {
                "path": relative(path),
                "width": image.width,
                "height": image.height,
                "bytes": path.stat().st_size,
                "animated": getattr(image, "is_animated", False),
            }
    except OSError:
        return None


def save_static_webp(source: Path, target: Path, quality: int) -> bool:
    with Image.open(source) as image:
        if image.mode not in {"RGB", "RGBA"}:
            image = image.convert("RGBA" if "A" in image.getbands() else "RGB")
        image.save(target, "WEBP", quality=quality, method=6)
    return target.exists() and target.stat().st_size < source.stat().st_size


def save_animated_webp(source: Path, target: Path, quality: int) -> bool:
    with Image.open(source) as image:
        frames = []
        durations = []
        for frame in ImageSequence.Iterator(image):
            frames.append(frame.convert("RGBA"))
            durations.append(frame.info.get("duration", image.info.get("duration", 80)))

        if not frames:
            return False

        frames[0].save(
            target,
            "WEBP",
            save_all=True,
            append_images=frames[1:],
            duration=durations,
            loop=image.info.get("loop", 0),
            quality=quality,
            method=0,
        )
    return target.exists() and target.stat().st_size < source.stat().st_size


def write_variant(path: Path, quality: int, min_bytes: int) -> Path | None:
    if path.suffix.lower() not in SOURCE_SUFFIXES or path.stat().st_size < min_bytes:
        return None

    target = path.with_suffix(".webp")
    try:
        with Image.open(path) as image:
            animated = getattr(image, "is_animated", False)
        ok = save_animated_webp(path, target, quality) if animated else save_static_webp(path, target, quality)
    except OSError as exc:
        print(f"warning: could not optimize {relative(path)}: {exc}")
        return None

    if ok:
        return target

    if target.exists():
        target.unlink()
    return None


def manifest_rows() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for path in sorted(IMAGE_ROOT.rglob("*")):
        if path.suffix.lower() not in SOURCE_SUFFIXES | {".webp", ".avif"}:
            continue

        info = image_info(path)
        if not info:
            continue

        webp = path.with_suffix(".webp")
        if path.suffix.lower() != ".webp" and webp.exists():
            info["webp"] = relative(webp)
            info["webp_bytes"] = webp.stat().st_size
        rows.append(info)
    return rows


def write_manifest(rows: list[dict[str, object]]) -> None:
    lines = ["# Generated by scripts/optimize_images.py", "images:"]
    for row in rows:
        lines.append(f"  - path: {row['path']}")
        lines.append(f"    width: {row['width']}")
        lines.append(f"    height: {row['height']}")
        lines.append(f"    bytes: {row['bytes']}")
        lines.append(f"    animated: {str(row['animated']).lower()}")
        if row.get("webp"):
            lines.append(f"    webp: {row['webp']}")
            lines.append(f"    webp_bytes: {row['webp_bytes']}")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*", help="optional image paths to optimize before writing the manifest")
    parser.add_argument("--write-variants", action="store_true", help="write smaller WebP variants for large images")
    parser.add_argument("--include-animated", action="store_true", help="include animated images during broad variant generation")
    parser.add_argument("--quality", type=int, default=82)
    parser.add_argument("--min-bytes", type=int, default=1_000_000)
    args = parser.parse_args()

    variants: list[Path] = []
    if args.write_variants:
        if args.paths:
            candidates = [ROOT / path for path in args.paths]
        else:
            candidates = sorted(IMAGE_ROOT.rglob("*"))

        for path in candidates:
            if path.suffix.lower() == ".webp":
                continue
            if not args.paths and not args.include_animated:
                info = image_info(path)
                if info and info["animated"]:
                    continue
            variant = write_variant(path, args.quality, args.min_bytes)
            if variant:
                variants.append(variant)

    rows = manifest_rows()
    write_manifest(rows)
    print(f"manifest images: {len(rows)}")
    print(f"webp variants written: {len(variants)}")
    for variant in variants:
        print(f"  {relative(variant)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
